# Project: linkedList
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = linkedList/linkedList/linkedList.o linkedList/linkedList/main.o
LINKOBJ  = linkedList/linkedList/linkedList.o linkedList/linkedList/main.o
LIBS     = -L"E:/g/Dev-Cpp/MinGW64/lib" -L"E:/g/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/g/Dev-Cpp/MinGW64/include" -I"E:/g/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/g/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/g/Dev-Cpp/MinGW64/include" -I"E:/g/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/g/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/g/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = linkedList.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

linkedList/linkedList/linkedList.o: linkedList/linkedList/linkedList.c
	$(CC) -c linkedList/linkedList/linkedList.c -o linkedList/linkedList/linkedList.o $(CFLAGS)

linkedList/linkedList/main.o: linkedList/linkedList/main.c
	$(CC) -c linkedList/linkedList/main.c -o linkedList/linkedList/main.o $(CFLAGS)
